version: 2.1
# Define the jobs we want to run for this project
jobs:
 build:
   docker:
      - image: alpine  
   steps:
      - run: echo "this is the test job"

# Orchestrate our job run sequence
workflows:
  commit:
    jobs:
      - build
