# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 42536768f866ff9cae2080fe5475077ea9c778fd0b398cd9c24874d0f8672c60b88c664f23ea16728b7c9864ab54ca5d6673a5db45c562c9b1c89ae2c1363261

test:
  secret_key_base: f97e748078342204a3480d6dd4bbfffb311c4f8c6340339e996dc145e8fb6913bab3eac3e2f7037c64a35838bd2e5fb7433ddcff75dfde5e840e7bd8ee6bfb2a

# Do not keep production secrets in the repository,
# instead read values from the environment.
assurance:
  secret_key_base: <%= ENV['SECRET_KEY_BASE'] %>

assurance2:
  secret_key_base: <%= ENV['SECRET_KEY_BASE'] %>

acceptance:
  secret_key_base: <%= ENV['SECRET_KEY_BASE'] %>


production:
  secret_key_base: 02f5dbaa215c33c317280689814fa0a5373fd9fd1a94ba11298722773c2bee3b2f4238d06bc7a58f064ba6d221c7574d96e79063b40199eb774c03dd69efa4a7
