# This is a basic workflow to help you get started with Actions

name: Publish

on:
 pull_request:
   branches: development
jobs:
  publish:
    name: Publish the package
    runs-on: ubuntu-latest
    steps:
      - name: Wait for build to succeed
        uses: fountainhead/action-wait-for-check@v1.0.0
        id: wait-for-build
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          checkName: commit
          ref: ${{ github.event.pull_request.head.sha || github.sha }}
          intervalSeconds: 10
          timeoutSeconds: 100
          
      - name: Do something if build isnot launch
        if: steps.wait-for-build.outputs.conclusion == 'does not exist'
        run: echo job does not exist && true

      - name: Do something with a passing built
        if: steps.wait-for-build.outputs.conclusion == 'success'
        run: ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.HOSTNAME }} && ls -lrth /tmp
