# This is a basic workflow to help you get started with Actions

name: Publish

on:
 pull_request:
   branches: development
 workflow_dispatch:
jobs:
  publish:
    name: Publish the package
    runs-on: ubuntu-latest
    steps:
      - name: Wait for build to succeed
        uses: fountainhead/action-wait-for-check@v1.0.0
        id: wait-for-build
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          checkName: commit
          ref: ${{ github.event.pull_request.head.sha || github.sha }}
          intervalSeconds: 10
          timeoutSeconds: 100
          
      - name: Do something if build isnot launch
        if: steps.wait-for-build.outputs.conclusion == 'does not exist'
        run: echo job does not exist && true
      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
         key: ${{ secrets.SSH_KEY }}
         known_hosts: ${{ secrets.HOSTNAME }}
         name: id_rsa # optional
         if_key_exists: fail
      - name: Do something with a passing built
        if: steps.wait-for-build.outputs.conclusion == 'success'
        run: ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.HOSTNAME }} && ls -lrth /tmp
        
  capistrano:
    name: configure capistrano
    runs-on: ubuntu-latest
#    needs: publish
    strategy:
      matrix:
        ruby-version: ['2.6.7']
    steps:
      - uses: actions/checkout@v2
      - uses: actions/dependency-review-action@v2
 
      - name: cap running
#        uses: ruby/setup-ruby@2b019609e2b0f1ea1a2bc8ca11cb82ab46ada124
        uses: ruby/setup-ruby@v1
        with:
         ruby-version: ${{ matrix.ruby-version }}
         bundler-cache: true # runs 'bundle install' and caches installed gems automatically
      
      - name: deploy app using Capistrano
        run: bundle exec cap production deploy
