name: Publish

on:
 pull_request:
   branches: development
#   types:
#     - closed
 workflow_dispatch:
 
jobs:
 if_merged:
    if: github.event.pull_request.merged == false
    name: start the process with runner
    runs-on: ubuntu-latest
    strategy:
       matrix:
          ruby-version: ['2.6.7']
    steps:
      - name: Wait for build to succeed
        uses: fountainhead/action-wait-for-check@v1.0.0
        id: wait-for-build
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          checkName: commit
          ref: ${{ github.event.pull_request.head.sha || github.sha }}
          intervalSeconds: 10
          timeoutSeconds: 100
          
      - name: Do something if build isnot launch
        if: steps.wait-for-build.outputs.conclusion == 'does not exist'
        run: echo job does not exist && true
      - name: Stop the process if circleci check failed
        if: steps.wait-for-build.outputs.conclusion == 'failure'
        run: exit 0
      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
         key: ${{ secrets.SSH_KEY }}
         known_hosts: ${{ secrets.HOSTNAME }}
         name: id_rsa # optional
         if_key_exists: fail
      - uses: actions/checkout@v2   
        
      - name: Do something with a passing built
        if: steps.wait-for-build.outputs.conclusion == 'failure'
        uses: ruby/setup-ruby@v1
        with:
         ruby-version: ${{ matrix.ruby-version }}
         run: gem install bundle
#         bundler-cache: true # runs 'bundle install' and caches installed gems automatically
      - name: deploy app using Capistrano
        if: steps.wait-for-build.outputs.conclusion == 'success'
        run: |
          eval "$(ssh-agent -s)"
          ssh-add ~/.ssh/id_rsa
          bundle exec cap production deploy
